import { db } from '@/db';
import { menuItems } from '@/db/schema';

async function main() {
    const sampleMenuItems = [
        // BREAKFAST ITEMS (18 items)
        {
            name: 'Idli (3 pieces)',
            description: 'Soft steamed rice cakes served with sambar and chutney',
            category: 'breakfast',
            price: 30.0,
            imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Plain Dosa',
            description: 'Crispy rice and lentil crepe',
            category: 'breakfast',
            price: 40.0,
            imageUrl: 'https://images.unsplash.com/photo-1630383249896-424e482df921',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Masala Dosa',
            description: 'Dosa filled with spiced potato masala',
            category: 'breakfast',
            price: 50.0,
            imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Onion Dosa',
            description: 'Crispy dosa topped with onions',
            category: 'breakfast',
            price: 45.0,
            imageUrl: 'https://images.unsplash.com/photo-1694159812780-0903d924379c',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Rava Dosa',
            description: 'Crispy semolina dosa',
            category: 'breakfast',
            price: 50.0,
            imageUrl: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Ghee Dosa',
            description: 'Dosa cooked in pure ghee',
            category: 'breakfast',
            price: 55.0,
            imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Pongal',
            description: 'Rice and lentil comfort food with pepper',
            category: 'breakfast',
            price: 40.0,
            imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Medu Vada (2 pieces)',
            description: 'Crispy lentil donuts',
            category: 'breakfast',
            price: 40.0,
            imageUrl: 'https://images.unsplash.com/photo-1626776876729-bab4cef75e34',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Sambar Vada',
            description: 'Vada soaked in sambar',
            category: 'breakfast',
            price: 45.0,
            imageUrl: 'https://images.unsplash.com/photo-1626776876729-bab4cef75e34',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Upma',
            description: 'Savory semolina breakfast',
            category: 'breakfast',
            price: 35.0,
            imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Poori with Potato Masala',
            description: 'Fried bread with spiced potato',
            category: 'breakfast',
            price: 45.0,
            imageUrl: 'https://images.unsplash.com/photo-1595777216528-071e0127ccf4',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Chapati with Kurma',
            description: 'Whole wheat flatbread with vegetable kurma',
            category: 'breakfast',
            price: 50.0,
            imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Puri Bhaji',
            description: 'Puri with potato bhaji',
            category: 'breakfast',
            price: 48.0,
            imageUrl: 'https://images.unsplash.com/photo-1595777216528-071e0127ccf4',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Idiyappam',
            description: 'String hoppers with coconut milk',
            category: 'breakfast',
            price: 40.0,
            imageUrl: 'https://images.unsplash.com/photo-1589301773859-cb0d2d4d0bc4',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Pesarattu',
            description: 'Green gram dosa',
            category: 'breakfast',
            price: 50.0,
            imageUrl: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Set Dosa (3 pieces)',
            description: 'Soft thick dosas',
            category: 'breakfast',
            price: 45.0,
            imageUrl: 'https://images.unsplash.com/photo-1630383249896-424e482df921',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Uthappam',
            description: 'Thick pancake with toppings',
            category: 'breakfast',
            price: 50.0,
            imageUrl: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Appam with Stew',
            description: 'Rice pancake with vegetable stew',
            category: 'breakfast',
            price: 55.0,
            imageUrl: 'https://images.unsplash.com/photo-1589301773859-cb0d2d4d0bc4',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // LUNCH ITEMS (25 items)
        {
            name: 'South Indian Meals',
            description: 'Complete thali with rice, sambar, rasam, curries',
            category: 'lunch',
            price: 90.0,
            imageUrl: 'https://images.unsplash.com/photo-1604085572504-a392ddf0d86a',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Mini Meals',
            description: 'Smaller portion thali',
            category: 'lunch',
            price: 80.0,
            imageUrl: 'https://images.unsplash.com/photo-1604085572504-a392ddf0d86a',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Special Meals',
            description: 'Premium thali with variety',
            category: 'lunch',
            price: 120.0,
            imageUrl: 'https://images.unsplash.com/photo-1604085572504-a392ddf0d86a',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Chicken Biryani',
            description: 'Aromatic rice with chicken',
            category: 'lunch',
            price: 150.0,
            imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Veg Biryani',
            description: 'Aromatic rice with vegetables',
            category: 'lunch',
            price: 100.0,
            imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Mutton Biryani',
            description: 'Aromatic rice with mutton',
            category: 'lunch',
            price: 180.0,
            imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Egg Biryani',
            description: 'Aromatic rice with boiled eggs',
            category: 'lunch',
            price: 120.0,
            imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Sambar Rice',
            description: 'Rice mixed with sambar',
            category: 'lunch',
            price: 70.0,
            imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Curd Rice',
            description: 'Cooling rice with yogurt',
            category: 'lunch',
            price: 60.0,
            imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Lemon Rice',
            description: 'Tangy lemon flavored rice',
            category: 'lunch',
            price: 65.0,
            imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Tamarind Rice',
            description: 'Tangy tamarind rice',
            category: 'lunch',
            price: 65.0,
            imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Chapati Meals',
            description: 'Chapati with dal and curry',
            category: 'lunch',
            price: 90.0,
            imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Parotta with Kurma',
            description: 'Layered flatbread with kurma',
            category: 'lunch',
            price: 70.0,
            imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Veg Fried Rice',
            description: 'Indo-Chinese fried rice',
            category: 'lunch',
            price: 80.0,
            imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Chicken Fried Rice',
            description: 'Fried rice with chicken',
            category: 'lunch',
            price: 110.0,
            imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Veg Noodles',
            description: 'Stir-fried noodles',
            category: 'lunch',
            price: 75.0,
            imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Chicken Noodles',
            description: 'Noodles with chicken',
            category: 'lunch',
            price: 105.0,
            imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Paneer Butter Masala with Roti',
            description: 'Cottage cheese in creamy tomato gravy',
            category: 'lunch',
            price: 120.0,
            imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Chole Bhature',
            description: 'Chickpea curry with fried bread',
            category: 'lunch',
            price: 95.0,
            imageUrl: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Meals with Rasam',
            description: 'Rice with rasam and sides',
            category: 'lunch',
            price: 85.0,
            imageUrl: 'https://images.unsplash.com/photo-1604085572504-a392ddf0d86a',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Fish Curry Meals',
            description: 'Meals with fish curry',
            category: 'lunch',
            price: 140.0,
            imageUrl: 'https://images.unsplash.com/photo-1604085572504-a392ddf0d86a',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Pulao',
            description: 'Mildly spiced rice',
            category: 'lunch',
            price: 80.0,
            imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Dal Fry with Rice',
            description: 'Lentil curry with rice',
            category: 'lunch',
            price: 75.0,
            imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Tomato Rice',
            description: 'Rice with tomato masala',
            category: 'lunch',
            price: 70.0,
            imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Jeera Rice',
            description: 'Cumin flavored rice',
            category: 'lunch',
            price: 65.0,
            imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // DINNER ITEMS (17 items)
        {
            name: 'Evening Idli (3 pieces)',
            description: 'Soft steamed rice cakes',
            category: 'dinner',
            price: 30.0,
            imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Evening Plain Dosa',
            description: 'Crispy rice crepe',
            category: 'dinner',
            price: 40.0,
            imageUrl: 'https://images.unsplash.com/photo-1630383249896-424e482df921',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Evening Masala Dosa',
            description: 'Dosa with potato filling',
            category: 'dinner',
            price: 50.0,
            imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Evening Rava Dosa',
            description: 'Crispy semolina dosa',
            category: 'dinner',
            price: 50.0,
            imageUrl: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Chapati Set',
            description: 'Chapati with dal and vegetable',
            category: 'dinner',
            price: 70.0,
            imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Parotta with Gravy',
            description: 'Parotta with vegetable gravy',
            category: 'dinner',
            price: 75.0,
            imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Evening Veg Fried Rice',
            description: 'Light fried rice',
            category: 'dinner',
            price: 85.0,
            imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Roti with Dal',
            description: 'Roti with lentil curry',
            category: 'dinner',
            price: 70.0,
            imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Mini Biryani',
            description: 'Small portion biryani',
            category: 'dinner',
            price: 90.0,
            imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Ghee Roast',
            description: 'Dosa roasted in ghee',
            category: 'dinner',
            price: 60.0,
            imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Paneer Dosa',
            description: 'Dosa with paneer filling',
            category: 'dinner',
            price: 80.0,
            imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Cheese Dosa',
            description: 'Dosa with cheese',
            category: 'dinner',
            price: 75.0,
            imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Mysore Masala Dosa',
            description: 'Spicy dosa with potato',
            category: 'dinner',
            price: 60.0,
            imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Spring Dosa',
            description: 'Dosa with vegetable filling',
            category: 'dinner',
            price: 70.0,
            imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Egg Dosa',
            description: 'Dosa with egg topping',
            category: 'dinner',
            price: 65.0,
            imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Podi Dosa',
            description: 'Dosa with spicy powder',
            category: 'dinner',
            price: 55.0,
            imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Schezwan Fried Rice',
            description: 'Spicy Chinese fried rice',
            category: 'dinner',
            price: 95.0,
            imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b',
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(menuItems).values(sampleMenuItems);
    
    console.log('✅ Menu items seeder completed successfully - 60 South Indian items added');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});